name = "jotkey"
version = "2.0.0"
description = "Convert jot documents to lustre elements. Can convert to custom renderers"
licences = ["Apache-2.0"]

repository = { type = "github", user = "ray-delossantos", repo = "jotkey" }

links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/ray-delossantos" },
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
jot = ">= 1.0.2 and < 2.0.0"
lustre = ">= 4.4.1 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.3 and < 2.0.0"
